### ISSUE TITLE
add "ReceipeRecommender" canvas to examples

### ISSUE THREAD

**Issue by gernotstarke** [arc42/canvas.arc42.org-site#36]
[ ] add image (thumbnail plus larger version) similar to other examples
[ ] add page with additional explanation for this specific canvas (start with ReceipeRecommender...)

**Comment by Per-Starke** [comment]
@gernotstarke fyi:

I've updated the gallery liquid / html plus css, so that you can easily add a button to the page with additional information below each canvas-example-image. Just add ```btn-link: link/to/page``` to the YAML front matter of the gallery, and the button will appear below the image of the canvas example. 

For the RecipeRecommender Canvas, the front matter now looks like this:
``` 
  - url: /examples/acc-RecipeRecommender-1920px.webp
    image_path: /examples/acc-RecipeRecommender-400px.webp
    alt: "architecture communication canvas for RecipeRecommender"
    title: "RecipeRecommender, from the Bachelor Thesis of Per Starke"
    btn-link: /canvas-details/acc-recipe-recommender
```

If you don't add btn-link to an image, no button will appear and everything stays as it was, so this front matter
```
  - url: /examples/acc-4-htmlSanityCheck.png.webp
    image_path: /examples/acc-4-htmlSanityCheck.400px.webp
    alt: "architecture communication canvas for HtmlSanityChecker"
    title: "HtmlSanityChecker"
```
Does not add any button below the image.

**Comment by Per-Starke** [comment]
@gernotstarke I've added a details-page for the RR-canvas, please have a quick look if this is like you imagined :)

**Comment by gernotstarke** [comment]
exactly as I envisioned. Very well done :-)

**Comment by Per-Starke** [comment]
@gernotstarke good to read! 

Please don't forget the overlay_filter for the header! I've added it for the status canvas page now, but otherwise the header will be nearly unreadable. 

Shall I add any more canvas details pages, or will you do that and I can close this issue?
